#─────────────── NETWORK ─────────────────────
networks:
  inception:
    driver: bridge

#─────────────── VOLUMES ─────────────────────
volumes:
  mariadb_data:
    name: inception_mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/edetoh/data/mariadb
      o: bind
  wordpress_data:
    name: inception_wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/edetoh/data/wordpress
      o: bind
  adminer_data:
    name: inception_adminer_data
    driver: local
    driver_opts:
      type: none
      device: /home/edetoh/data/adminer
      o: bind

#─────────────── SERVICES ─────────────────────
services:
  mariadb:
    build: ./mariaDB
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${SQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    build: ./WordPress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: always
    image: wordpress

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
      - adminer_data:/var/www/adminer
    depends_on:
      - wordpress
      - adminer
    networks:
      - inception
    ports:
      - "443:443"
      - "6969:6969"
    restart: always

  adminer:
    build: ./adminer
    container_name: adminer
    image: adminer
    env_file:
      - .env
    volumes:
      - adminer_data:/var/www/adminer
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always